### ISSUE TITLE
No osx-arm64 built

### ISSUE THREAD

**Issue by mjwen** [conda-forge/kliff-feedstock#24]
### Comment:

There are osx-64 and linux-64 builds, but no osx-arm64. I'm checking it from https://anaconda.org/conda-forge/kliff/files 

@jan-janssen and @ilia-nikiforov-umn: any idea how to enable that?

**Comment by jan-janssen** [comment]
I opened a corresponding pull request https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5291

**Comment by mjwen** [comment]
Resolved in #25
